### ISSUE TITLE
Recoverable fatal error: wp-includes/kses.php on line 1592

### ISSUE THREAD

**Issue by fhfournier** [RTO-Websites/dynamic-conditions#23]
Hi,

I"m using Elementor, ElementorPro, ElementorExtra, JetEngine, JetElement.

If im running all theses Elementor plugin without "DynamicConditions" all works but when i activate your plugin, there is the error i got. Blank page with this

Recoverable fatal error: Object of class WP_Error could not be converted to string in [PATH]/wp-includes/kses.php on line 1592

![image](https://user-images.githubusercontent.com/3278753/69756828-6a1f7800-1129-11ea-84f2-0307317445ec.png)

**Comment by Enoray** [comment]
Hello @fhfournier,

we will try to investigate, can you maybe isolate the plugin combonation that not works?

Thank you!

**Comment by SecretProtonium** [comment]
Hello @fhfournier,

can you please provide us more information about your environment and configuration. So that we can reproduce the Bug, to productively investigate him. It would be nice, if you can provide us the following things:

- The WordPress version which you used to encounter the bug.
- All plugins that were activated when the error occurred, including their version.
- Your WordPress settings, as all settings from the activated plugins.
- Configurations you done using some of the activated plugins.

<hr>

**Kind regards**

SecretProtonium

Member of [RTO-Websites](https://github.com/RTO-Websites)

**Comment by fhfournier** [comment]
Hi,

Wordpress 4.3

DynamicConditions 1.4.1
Elementor 2.7.5
Elementor Pro 2.7.3

All other plugins are deactivated

**Comment by Enoray** [comment]
Did you try it with a clean installation and just this Plugins or did you just disabled other Plugins after they was activated?

I ask this, because we never got any reports about an issue like that.

Can you give as a step by step instruction how to reproduce this issue?

Thank you.

**Comment by Enoray** [comment]
Ohh i see it is Wordpress 4.3 not 5.3. 
We are sorry, but this Version is not supported by our Plugin. Please use Wordpress 4.7 or Higher.

**Comment by fhfournier** [comment]
My bad, its 5.3

**Comment by crazypsycho** [comment]
Hello,

the error-messages rows in your screenshots goes from 17-51. Can you show us row 1-17?
This could help to see where the error occours.

Thank you

**Comment by fhfournier** [comment]
I delete my local site with debug, its all WordPress initial command

**Comment by Enoray** [comment]
We can't reproduce it, you deleted your local site so we closed the issue
