### ISSUE TITLE
Not Recognizing Pagination URLs in Acrhives

### ISSUE THREAD

**Issue by JeremyL** [RTO-Websites/dynamic-conditions#28]
Not sure if this is a feature request or a bug. But when I tell it to check the Archive URL as a condition it does not recognize any of the pagination parts.

I want to filter on /page/:
- /blog/page/2/
- /category/credit/page/2/

But it only recognizes 
- /blog/
- /category/credit/

Would be really helpful if it could see the extra part of the URL.

**Comment by crazypsycho** [comment]
Hello,

i think you could use "Request parameter" instead of archive url.
There you can select query var as type and enter "paged" as parameter name.
This should give you the current page-number.

![image](https://user-images.githubusercontent.com/12948745/74584720-a39fab00-4fd5-11ea-8b65-cd33217fdb20.png)

**Comment by JeremyL** [comment]
You sir are a lifesaver. I tried Query Var page, not paged. It worked. 

Thanks!
