### ISSUE TITLE
Dynamic Conditions shows image/media selection?

### ISSUE THREAD

**Issue by barrychapman** [RTO-Websites/dynamic-conditions#31]
In the place where the dynamic tags selection is (it is still there, albeit small and hidden), it displays a selection for media. Why is that there? What purpose does it serve?

![image](https://user-images.githubusercontent.com/152958/76726366-4a877c00-6727-11ea-93e8-7685e6d967ee.png)

**Comment by crazypsycho** [comment]
In order to have all tags of every type available, we had to use Image as the type.
So far this was not a problem and we were able to adapt the design using CSS.
Elementor changed the design for the DynamicTags with 2.9.
It has become a little more complex, which is why we decided to no longer adapt it.
That's why you now have a media select
